version: '3'
services:
  dev:
    build:
        context: .
        dockerfile: Dockerfile
    privileged: true
    volumes:
        - .:/code
    ports:
        - 4000:4000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
    phoenix_code:
